### ISSUE TITLE
Bun support?

### ISSUE THREAD

**Issue by Murtatrxx** [sern-handler/cord#18]
Can we provide bun support? Or at least test?

**Comment by jacoobes** [comment]
This was discussed in the discord, but at the moment there are no plans. Bun only supports linux at the moment, Feel free to create your own branch and experiment, trying to get serncord to run on bun

**Comment by Murtatrxx** [comment]
👍👍

**Comment by SrIzan10** [comment]
serncord might just run bun out of the box, I'll try it out *eventually*
